# Generated by Django 3.2.9 on 2021-12-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_defuser_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='fio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=120, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Не выбрано'), (1, '3D-дизайн'), (2, '2D-дизайн'), (3, 'Эскиз')], default=0, verbose_name='category')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'В обработке'), (1, 'Принято в работу'), (2, 'Выполнено')], default=0, null=True, verbose_name='status')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Заявки')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
