# Generated by Django 3.2.9 on 2021-12-09 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211208_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='category',
            field=models.CharField(choices=[('Не выбрано', 'Не выбрано'), ('3D-дизайн', '3D-дизайн'), ('2D-дизайн', '2D-дизайн'), ('Эскиз', 'Эскиз')], default='Не выбрано', max_length=120, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принято в работу', 'Принято в работу'), ('Выполнено', 'Выполнено')], default='Новая', max_length=120, null=True, verbose_name='status'),
        ),
    ]
