# Generated by Django 3.2.9 on 2021-12-15 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_addcommentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
